print("Hello world")
print("1. Mix 500 of Flour, 10g Yeast and 300ml water in a bowl.")
print("2. Knead the dough for 10 minutes.")
print("3. Add 3g of salt.")
print("4. Leave to roise for 2 hours.")
print("5. Bake at 200 degrees C for 30 minutes.")
print("A 'sigle quote' inside double quote")
print('A "double quote" inside a single quote')
print("Alternatively you can just \"escape\" the quote")